/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.shows;

import controller.shows.ShowsController;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author marco
 */
public class ShowsView extends javax.swing.JDialog {
    ShowsController showsController;
    /**
     * Creates new form ShowsView2
     */
    public ShowsView(java.awt.Frame parent, boolean modal, ShowsController controller) {
        super(parent, modal);
        initComponents();
        this.showsController = controller;
        showsController.getAllShows(tableShows);
    }

    private ShowsView(JFrame jFrame, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableShows = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        seeResponsibleButton = new javax.swing.JButton();
        cancelShowButton = new javax.swing.JButton();
        watchFunctions = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Shows ofrecidos");

        tableShows.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "name", "descripcion", "precio base", "estatus", "actores", "publicidad"
            }
        ));
        jScrollPane1.setViewportView(tableShows);

        jLabel2.setText("Seleccione un show primero");

        seeResponsibleButton.setText("Ver responsable");
        seeResponsibleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seeResponsibleButtonActionPerformed(evt);
            }
        });

        cancelShowButton.setText("Cancelar show");
        cancelShowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelShowButtonActionPerformed(evt);
            }
        });

        watchFunctions.setText("Ver funciones de esta obra");
        watchFunctions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                watchFunctionsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 889, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(seeResponsibleButton)
                        .addGap(75, 75, 75)
                        .addComponent(cancelShowButton)
                        .addGap(66, 66, 66)
                        .addComponent(watchFunctions))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seeResponsibleButton)
                    .addComponent(cancelShowButton)
                    .addComponent(watchFunctions))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seeResponsibleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seeResponsibleButtonActionPerformed
        int showSelected = tableShows.getSelectedRow();
            
        if(showSelected != -1){
            int idShow = (int) tableShows.getValueAt(showSelected, 0);
            showsController.seeResponsibleShow(idShow);
        }else{
            JOptionPane.showMessageDialog(this, "Seleccione primero una obra");
        }
    }//GEN-LAST:event_seeResponsibleButtonActionPerformed

    private void cancelShowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelShowButtonActionPerformed
        int showSelected = tableShows.getSelectedRow();
            
        if(showSelected != -1){
            int dialogResult = JOptionPane.showConfirmDialog(this, "Cancelar el show, implica cancelar las funciones hechas\n ¿desea continuar la cancelacion?");

            if(dialogResult == JOptionPane.YES_OPTION){               
                int idShow = (int) tableShows.getValueAt(showSelected, 0);
                showsController.cancelFunctionRelated(idShow);
                JOptionPane.showMessageDialog(this, "Show cancelado");                
            }
        }else{
            JOptionPane.showMessageDialog(this, "Seleccione primero una obra");
        }          
    }//GEN-LAST:event_cancelShowButtonActionPerformed

    private void watchFunctionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_watchFunctionsActionPerformed
        int showSelected = tableShows.getSelectedRow();
            
        if(showSelected != -1){
            int idShow = (int) tableShows.getValueAt(showSelected, 0);
            showsController.openFuncionRelatedView(idShow);
        }else{
            JOptionPane.showMessageDialog(this, "Seleccione primero una obra");
        }
    }//GEN-LAST:event_watchFunctionsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ShowsView dialog = new ShowsView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton cancelShowButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton seeResponsibleButton;
    public javax.swing.JTable tableShows;
    public javax.swing.JButton watchFunctions;
    // End of variables declaration//GEN-END:variables
}
